/*
 * SEAL - utility for collecting information about files in runtime
 * Copyright (C) 2023 Samsung Electronics Co., Ltd.
 */

#ifndef SEAL_PASSTHROUGH_H
#define SEAL_PASSTHROUGH_H

char *passthrough_functions[] = {
//	"ashmem_read_iter",
//	"blkdev_read_iter",
	"bus_attr_show",
	"cgroup_seqfile_show",
	"class_attr_show",
	"configfs_read_file",
	"configfs_read_iter",
	"cpuidle_state_show",
	"debugfs_attr_read",
	"dev_attr_show",
	"dm_attr_show",
	"drv_attr_show",
	"elv_attr_show",
//	"erofs_file_read_iter",
//	"ext4_file_read_iter",
	"f2fs_attr_show",
//	"f2fs_file_read_iter",
	"fb_read",
//	"ffs_epfile_read_iter",
	"full_proxy_read",
//	"fuse_file_read_iter",
//	"generic_file_read_iter",
	"iio_read_channel_info",
	"iommu_group_attr_show",
	"kernfs_fop_read",
	"kernfs_fop_read_iter",
	"kernfs_seq_show",
	"kobj_attr_show",
	"module_attr_show",
	"netdev_queue_attr_show",
	"param_attr_show",
	"proc_reg_read",
	"proc_reg_read_iter",
	"proc_sys_read",
	"pstore_file_read",
	"queue_attr_show",
//	"read_iter_zero",
	"rx_queue_attr_show",
	"seq_read",
//	"shmem_file_read_iter",
	"slab_attr_show",
	"snd_hwdep_read",
	"sysfs_kf_bin_read",
	"sysfs_kf_read",
	"sysfs_kf_seq_show",
	"tracing_read_pipe",
	"tty_read",
//	"tun_chr_read_iter",
	"uevent_show",
	"v4l2_read",

//	"blkdev_write_iter",
	"bus_attr_store",
	"cgroup_file_write",
	"class_attr_store",
	"configfs_write_file",
	"configfs_write_iter",
	"cpuidle_state_store",
	"debugfs_attr_write",
	"dev_attr_store",
	"dm_attr_store",
	"elv_attr_store",
	"event_trigger_write",
//	"ext4_file_write_iter",
	"f2fs_attr_store",
//	"f2fs_file_write_iter",
	"fb_write",
//	"ffs_epfile_write_iter",
	"full_proxy_write",
//	"fuse_file_write_iter",
//	"generic_file_write_iter",
	"iio_write_channel_info",
	"iommu_group_attr_store",
	"kernfs_fop_write",
	"kernfs_fop_write_iter",
	"kobj_attr_store",
	"module_attr_store",
	"netdev_queue_attr_store",
	"param_attr_store",
	"proc_reg_write",
	"proc_sys_write",
	"queue_attr_store",
	"rx_queue_attr_store",
	"simple_attr_write",
	"slab_attr_store",
	"snd_hwdep_write",
	"sysfs_kf_bin_write",
	"sysfs_kf_write",
	"trace_options_write",
	"tty_write",
//	"tun_chr_write_iter",
	"uevent_store",
	"v4l2_write",

	"fb_mmap",
	"kernfs_fop_mmap",
	"proc_reg_mmap",
	"snd_hwdep_mmap",
	"sysfs_kf_bin_mmap",
	"v4l2_mmap",

	"block_ioctl",
	"fb_ioctl",
	"lo_ioctl",
	"proc_reg_unlocked_ioctl",
	"sd_ioctl",
	"snd_ctl_ioctl",
	"snd_hwdep_ioctl",
	"tty_ioctl",
	"v4l2_ioctl",

/*	compat ioctls:
	"compat_blkdev_ioctl",
	"fb_compat_ioctl",
	"proc_reg_unlocked_ioctl",
	"snd_ctl_ioctl_compat",
	"snd_hwdep_ioctl_compat",
	"tty_compat_ioctl",
	"v4l2_compat_ioctl32",
 */
};

#endif /* SEAL_PASSTHROUGH_H */
